import { IssueData } from './types';

const today = new Date().toISOString().split('T')[0];

export const DEMO_DATA: Record<string, IssueData> = {
  "Alcohol": {
    meta: {
      sector: "Alcohol",
      generated_at: today,
      week_number: 13,
      capped: false,
    },
    sections: {
      regulatory_updates: [
        {
          original_url: "https://www.abac.org.au",
          section: "regulatory_update",
          headline: "ABAC updates responsible alcohol marketing code guidance",
          summary: "The Alcohol Beverages Advertising Code has released updated guidance on digital and social media placements, clarifying that influencer partnerships require the same disclosures as traditional advertising.",
          action: "Review all influencer partnership agreements to ensure ABAC disclosure requirements are met in every post.",
          sector_tags: ["alcohol"],
          source: "ABAC",
        },
        {
          original_url: "https://adstandards.com.au",
          section: "regulatory_update",
          headline: "Ad Standards upholds complaint against alcohol brand lifestyle imagery",
          summary: "A complaint against a beer brand's outdoor campaign was upheld after imagery was found to associate alcohol consumption with active outdoor lifestyles, breaching ABAC Section 3(a).",
          action: "Audit any lifestyle imagery in current campaigns for implied health or performance associations.",
          sector_tags: ["alcohol"],
          source: "Ad Standards",
        },
      ],
      judgements: [
        {
          original_url: "https://www.abac.org.au",
          section: "judgement",
          headline: "ABAC Det. 25/26 — spirits brand social post found in breach",
          summary: "An Instagram post by a spirits brand was found to breach ABAC by depicting consumption in a context appealing to under-18s through the use of cartoon-style imagery and bright colours.",
          action: "Remove cartoon or animated elements from alcohol advertising that could appeal to minors.",
          sector_tags: ["alcohol"],
          source: "ABAC",
        },
        {
          original_url: "https://adstandards.com.au",
          section: "judgement",
          headline: "Ad Standards dismisses complaint against Coopers Brewery campaign",
          summary: "A complaint alleging a Coopers campaign promoted irresponsible consumption was dismissed. The panel found the creative depicted moderate, social consumption consistent with ABAC guidelines.",
          action: "No immediate action required — decision confirms current best-practice approach to social consumption depictions.",
          sector_tags: ["alcohol"],
          source: "Ad Standards",
        },
        {
          original_url: "https://www.accc.gov.au",
          section: "judgement",
          headline: "ACCC warns alcohol brands on comparative pricing claims",
          summary: "The ACCC has issued guidance warning that 'cheapest' and 'best value' claims in alcohol advertising require robust substantiation, following several complaints about misleading pricing.",
          action: "Substantiate all comparative pricing claims with documented evidence before publishing.",
          sector_tags: ["alcohol"],
          source: "ACCC",
        },
      ],
      under_review: [
        {
          original_url: "https://www.abac.org.au",
          section: "under_review",
          headline: "ABAC consultation open on influencer marketing code update",
          summary: "ABAC is consulting on proposed changes to the code that would require clearer disclosure of paid influencer arrangements for alcohol brands, including minimum font size and placement requirements.",
          action: "Review proposed changes and consider submitting feedback before the consultation closes 30 April 2026.",
          sector_tags: ["alcohol"],
          source: "ABAC",
        },
      ],
    },
    compliance_tip: "Alcohol ads must not target under-18s. Under the ABAC Responsible Alcohol Marketing Code, alcohol advertising must never directly or indirectly appeal to people under 18 — including placement, imagery, language, and social media distribution.",
    sector_spotlight: "The alcohol advertising landscape is tightening significantly. ABAC enforcement has focused heavily on social media content, influencer partnerships, and digital placements. Key risks: user-generated content that brands don't directly create, lifestyle imagery implying health benefits, and influencer posts that don't meet disclosure requirements. Practical tip: audit your social media guidelines and influencer contracts now.",
  },

  "Food and Beverage": {
    meta: {
      sector: "Food and Beverage",
      generated_at: today,
      week_number: 13,
      capped: false,
    },
    sections: {
      regulatory_updates: [
        {
          original_url: "https://www.foodstandards.gov.au",
          section: "regulatory_update",
          headline: "FSANZ updates health star rating display requirements",
          summary: "Food Standards Australia New Zealand has updated guidance on health star rating displays in advertising, requiring that ratings shown in ads match current product labels without rounding.",
          action: "Cross-check all advertised health star ratings against current approved product labels.",
          sector_tags: ["food_beverage"],
          source: "FSANZ",
        },
        {
          original_url: "https://adstandards.com.au",
          section: "regulatory_update",
          headline: "Ad Standards issues guidance on children's food advertising",
          summary: "Ad Standards has clarified that food advertising during children's programming must not use promotional characters, celebrities, or premium offers to encourage purchases of HFSS products.",
          action: "Review any campaigns running during or adjacent to children's programming for compliance with the children's advertising code.",
          sector_tags: ["food_beverage"],
          source: "Ad Standards",
        },
      ],
      judgements: [
        {
          original_url: "https://adstandards.com.au",
          section: "judgement",
          headline: "Ad Standards upholds complaint against fast food portion size claims",
          summary: "A complaint against a QSR brand's 'biggest ever' meal promotion was upheld after evidence showed the claim was not substantiated against comparable market offerings.",
          action: "Substantiate all superlative claims ('biggest', 'best', 'most') with documented evidence before publishing.",
          sector_tags: ["food_beverage"],
          source: "Ad Standards",
        },
        {
          original_url: "https://www.accc.gov.au",
          section: "judgement",
          headline: "ACCC takes action against misleading 'natural' food claims",
          summary: "The ACCC has commenced proceedings against a food brand using 'all natural' claims on products containing artificial preservatives, alleging the claims are misleading under the ACL.",
          action: "Audit all 'natural', 'clean', and 'wholesome' claims against ingredient lists immediately.",
          sector_tags: ["food_beverage"],
          source: "ACCC",
        },
        {
          original_url: "https://adstandards.com.au",
          section: "judgement",
          headline: "Ad Standards dismisses complaint against Cadbury campaign",
          summary: "A complaint alleging a Cadbury chocolate campaign encouraged overconsumption was dismissed, with the panel finding the creative depicted occasional, moderate enjoyment within community standards.",
          action: "No action required — confirms that enjoyment-focused confectionery advertising remains within standards.",
          sector_tags: ["food_beverage"],
          source: "Ad Standards",
        },
      ],
      under_review: [
        {
          original_url: "https://www.accc.gov.au",
          section: "under_review",
          headline: "ACCC reviewing online food delivery platform advertising standards",
          summary: "The ACCC has opened a review into advertising practices on food delivery platforms, including whether promotional pricing and urgency claims meet ACL requirements.",
          action: "Monitor this review if your brand advertises on Uber Eats, DoorDash, or similar platforms.",
          sector_tags: ["food_beverage"],
          source: "ACCC",
        },
      ],
    },
    compliance_tip: "Every comparison must be accurate, not misleading, and based on like-for-like criteria. ACCC has actioned multiple cases where 'Australia's #1' style claims lacked substantiation.",
    sector_spotlight: "The food and beverage sector faces increasing scrutiny on health and nutrition claims. FSANZ and ACCC are coordinating on misleading health star rating and 'natural' claim enforcement. Key risk: implied health benefits through imagery or lifestyle associations that aren't substantiated. Practical tip: treat any visual or verbal health association as a formal health claim requiring substantiation.",
  },

  "Supplements": {
    meta: {
      sector: "Supplements",
      generated_at: today,
      week_number: 13,
      capped: false,
    },
    sections: {
      regulatory_updates: [
        {
          original_url: "https://www.tga.gov.au",
          section: "regulatory_update",
          headline: "TGA issues guidance on therapeutic claim substantiation requirements",
          summary: "The Therapeutic Goods Administration has released updated guidance clarifying that all therapeutic claims in advertising must be supported by evidence listed in the ARTG, regardless of media channel.",
          action: "Audit all supplement advertising claims against current ARTG listings before next campaign flight.",
          sector_tags: ["supplements"],
          source: "TGA",
        },
        {
          original_url: "https://adstandards.com.au",
          section: "regulatory_update",
          headline: "Ad Standards clarifies rules on before and after imagery in supplement ads",
          summary: "Ad Standards has issued guidance confirming that before-and-after transformation imagery in supplement advertising raises significant concerns under community standards, particularly where results are atypical.",
          action: "Remove or add clear disclaimers to any before-and-after imagery in current creative.",
          sector_tags: ["supplements"],
          source: "Ad Standards",
        },
      ],
      judgements: [
        {
          original_url: "https://www.tga.gov.au",
          section: "judgement",
          headline: "TGA issues infringement notice to supplements brand for TGA unapproved claims",
          summary: "A sports nutrition brand received a TGA infringement notice for advertising therapeutic effects of a protein supplement without holding the required ARTG listing for those specific claims.",
          action: "Verify every therapeutic claim in your advertising is supported by a current ARTG listing.",
          sector_tags: ["supplements"],
          source: "TGA",
        },
        {
          original_url: "https://adstandards.com.au",
          section: "judgement",
          headline: "Ad Standards upholds complaint against weight loss supplement testimonial",
          summary: "A complaint was upheld against a supplement brand's use of a celebrity testimonial claiming dramatic weight loss results, finding the claim was unsubstantiated and likely to mislead consumers.",
          action: "Obtain and retain documented evidence for all testimonial claims before publishing.",
          sector_tags: ["supplements"],
          source: "Ad Standards",
        },
        {
          original_url: "https://www.accc.gov.au",
          section: "judgement",
          headline: "ACCC warns supplements industry on subscription trap practices",
          summary: "The ACCC has warned supplements brands about subscription auto-renewal practices in advertising, stating that material terms must be clearly disclosed at the point of purchase promotion.",
          action: "Review all subscription offer advertising to ensure auto-renewal terms are prominently disclosed.",
          sector_tags: ["supplements"],
          source: "ACCC",
        },
      ],
      under_review: [
        {
          original_url: "https://www.tga.gov.au",
          section: "under_review",
          headline: "TGA consulting on social media advertising rules for listed medicines",
          summary: "The TGA has opened consultation on proposed rules that would require all social media advertising for listed therapeutic goods to include standardised risk disclaimers regardless of character limits.",
          action: "Review proposed rules and prepare adjusted social media templates for potential compliance.",
          sector_tags: ["supplements"],
          source: "TGA",
        },
      ],
    },
    compliance_tip: "Any health or wellness claim must be supported by credible scientific evidence. The TGA requires therapeutic claims — including implied ones — are backed by evidence before publication, not after a complaint.",
    sector_spotlight: "The TGA is actively enforcing advertising rules for supplements and listed therapeutic goods. Infringement notices are increasing. Key risk areas: social media influencer posts making therapeutic claims, before-and-after imagery without disclaimers, and subscription offers without clear terms. Practical tip: run every influencer brief through a compliance check before posting — influencer content is treated as brand advertising under TGA rules.",
  },

  "Gaming and Gambling": {
    meta: {
      sector: "Gaming and Gambling",
      generated_at: today,
      week_number: 13,
      capped: false,
    },
    sections: {
      regulatory_updates: [
        {
          original_url: "https://www.acma.gov.au",
          section: "regulatory_update",
          headline: "ACMA updates online gambling advertising placement rules",
          summary: "The Australian Communications and Media Authority has updated placement rules for online gambling advertising, restricting live odds promotions during sports broadcasts to specific time windows.",
          action: "Review media buying schedules to ensure gambling ads comply with updated ACMA placement restrictions.",
          sector_tags: ["gambling"],
          source: "ACMA",
        },
        {
          original_url: "https://adstandards.com.au",
          section: "regulatory_update",
          headline: "Ad Standards issues updated guidance on gambling harm messaging",
          summary: "Ad Standards has clarified that responsible gambling messaging must be genuinely prominent in all gambling advertising, and that fine-print or rapid voiceover delivery does not meet the prominence requirement.",
          action: "Audit responsible gambling message placement and duration across all current creative executions.",
          sector_tags: ["gambling"],
          source: "Ad Standards",
        },
      ],
      judgements: [
        {
          original_url: "https://adstandards.com.au",
          section: "judgement",
          headline: "Ad Standards upholds complaint against wagering brand inducement offer",
          summary: "A complaint against a wagering brand's 'bet $50 get $100' promotion was upheld after the panel found the terms were not adequately disclosed in the advertising, breaching AANA Wagering Code s2.4.",
          action: "Ensure all inducement offer terms are clearly disclosed within the advertising itself, not just on linked landing pages.",
          sector_tags: ["gambling"],
          source: "Ad Standards",
        },
        {
          original_url: "https://www.accc.gov.au",
          section: "judgement",
          headline: "ACCC takes action against gambling platform on misleading odds claims",
          summary: "The ACCC commenced proceedings against an online wagering platform for advertising 'best odds guaranteed' without being able to substantiate the claim across all market conditions.",
          action: "Review all 'best odds' and comparative wagering claims for substantiation.",
          sector_tags: ["gambling"],
          source: "ACCC",
        },
        {
          original_url: "https://adstandards.com.au",
          section: "judgement",
          headline: "Ad Standards dismisses complaint against Ladbrokes campaign",
          summary: "A complaint alleging a Ladbrokes campaign encouraged excessive gambling was dismissed. The panel found the creative depicted social, incidental wagering within AANA Wagering Code standards.",
          action: "No action required — confirms current best-practice approach to social wagering depictions.",
          sector_tags: ["gambling"],
          source: "Ad Standards",
        },
      ],
      under_review: [
        {
          original_url: "https://www.acma.gov.au",
          section: "under_review",
          headline: "Federal government reviewing gambling advertising restrictions",
          summary: "A Senate inquiry into gambling advertising is underway with recommendations expected Q2 2026, potentially introducing pre-watershed broadcast restrictions and digital platform controls.",
          action: "Monitor inquiry progress and begin scenario planning for potential broadcast and digital restrictions.",
          sector_tags: ["gambling"],
          source: "ACMA",
        },
      ],
    },
    compliance_tip: "Ad Standards requires responsible gambling messaging to be genuinely prominent in all gambling advertising. Fine-print or rapid voiceover delivery does not meet the prominence requirement — messaging must be clearly legible and audible.",
    sector_spotlight: "The Senate inquiry into gambling advertising is the biggest regulatory development in the sector for a decade. Potential outcomes include pre-watershed broadcast bans, digital platform restrictions, and mandatory pre-commitment messaging. Key risk: brands that don't start planning now will face rushed creative and media changes. Practical tip: develop two campaign versions — one for current rules, one for the restricted scenario — so you're ready either way.",
  },

  "Insurance Broker": {
    meta: {
      sector: "Insurance Broker",
      generated_at: today,
      week_number: 13,
      capped: false,
    },
    sections: {
      regulatory_updates: [
        {
          original_url: "https://asic.gov.au",
          section: "regulatory_update",
          headline: "ASIC updates guidance on insurance product comparison advertising",
          summary: "ASIC has released updated RG234 guidance clarifying that insurance comparison advertising must not cherry-pick features and must present a balanced view of product benefits and limitations.",
          action: "Review all comparison advertising to ensure balanced feature presentation and remove any cherry-picked benefit claims.",
          sector_tags: ["insurance"],
          source: "ASIC",
        },
        {
          original_url: "https://adstandards.com.au",
          section: "regulatory_update",
          headline: "Ad Standards issues guidance on insurance urgency claims",
          summary: "Ad Standards has clarified that urgency claims in insurance advertising ('limited time offer', 'act now') must be genuine and not artificially created to pressure consumers into purchases.",
          action: "Audit all urgency claims in current insurance advertising for legitimacy and remove artificial urgency language.",
          sector_tags: ["insurance"],
          source: "Ad Standards",
        },
      ],
      judgements: [
        {
          original_url: "https://asic.gov.au",
          section: "judgement",
          headline: "ASIC takes action against insurer for misleading exclusion disclosure",
          summary: "ASIC commenced proceedings against an insurer for advertising comprehensive cover without adequately disclosing significant exclusions, finding the advertising likely to mislead consumers under the ACL.",
          action: "Ensure all significant exclusions are disclosed clearly in advertising, not just in PDS documents.",
          sector_tags: ["insurance"],
          source: "ASIC",
        },
        {
          original_url: "https://adstandards.com.au",
          section: "judgement",
          headline: "Ad Standards upholds complaint against life insurance emotional advertising",
          summary: "A complaint against a life insurance brand's campaign was upheld after the panel found the emotional imagery exploited consumer fears without providing balanced information about the product.",
          action: "Review emotional advertising executions to ensure fear-based messaging is balanced with factual product information.",
          sector_tags: ["insurance"],
          source: "Ad Standards",
        },
        {
          original_url: "https://www.accc.gov.au",
          section: "judgement",
          headline: "ACCC warns insurance brokers on undisclosed commission advertising",
          summary: "The ACCC has warned that insurance broker advertising must disclose when recommendations are influenced by commission arrangements, following complaints about misleading 'independent advice' claims.",
          action: "Review all 'independent' or 'unbiased' advice claims and add appropriate commission disclosure.",
          sector_tags: ["insurance"],
          source: "ACCC",
        },
      ],
      under_review: [
        {
          original_url: "https://asic.gov.au",
          section: "under_review",
          headline: "Treasury consulting on insurance broker fee disclosure requirements",
          summary: "Treasury has opened consultation on proposed reforms requiring insurance brokers to disclose all remuneration arrangements in advertising, not just at point of sale.",
          action: "Monitor consultation and prepare for potential advertising disclosure requirements from mid-2026.",
          sector_tags: ["insurance"],
          source: "ASIC",
        },
      ],
    },
    compliance_tip: "ASIC requires financial product advertising includes risk warnings in a manner that is clear, concise, and effective — not hidden in fine print or spoken rapidly at the end of a radio ad.",
    sector_spotlight: "ASIC is focused on ensuring insurance advertising gives consumers a genuinely balanced view of products. Key risk areas: exclusion disclosure, comparison advertising, and commission transparency. The upcoming Treasury consultation on broker fee disclosure may require significant changes to how brokers present their services. Practical tip: treat every insurance ad as if ASIC will review it — because increasingly, they do.",
  },

  "News and Publications": {
    meta: {
      sector: "News and Publications",
      generated_at: today,
      week_number: 13,
      capped: false,
    },
    sections: {
      regulatory_updates: [
        {
          original_url: "https://adstandards.com.au",
          section: "regulatory_update",
          headline: "Ad Standards updates native advertising disclosure guidelines",
          summary: "Ad Standards has issued updated guidance requiring that native advertising and sponsored content be clearly labelled in a manner that is immediately apparent to readers before they engage with the content.",
          action: "Audit all sponsored content and native advertising placements for clear, upfront disclosure labelling.",
          sector_tags: ["general"],
          source: "Ad Standards",
        },
        {
          original_url: "https://www.acma.gov.au",
          section: "regulatory_update",
          headline: "ACMA issues guidance on online news platform advertising standards",
          summary: "The Australian Communications and Media Authority has released guidance clarifying that online news platforms are subject to the same advertising standards as broadcast media for certain content categories.",
          action: "Review online advertising placements across news platforms for compliance with ACMA broadcast-equivalent standards.",
          sector_tags: ["general"],
          source: "ACMA",
        },
      ],
      judgements: [
        {
          original_url: "https://www.presscouncil.org.au",
          section: "judgement",
          headline: "APC upholds complaint against publication for undisclosed advertorial",
          summary: "The Australian Press Council upheld a complaint against a major publication for running advertorial content without adequate disclosure, finding the content was likely to be mistaken for independent editorial.",
          action: "Ensure all advertorial and branded content is labelled 'Sponsored' or 'Advertisement' in a prominent, upfront position.",
          sector_tags: ["general"],
          source: "APC",
        },
        {
          original_url: "https://adstandards.com.au",
          section: "judgement",
          headline: "Ad Standards dismisses complaint against news brand programmatic advertising",
          summary: "A complaint against a news publisher's programmatic advertising adjacency was dismissed, with the panel finding the publisher had implemented reasonable brand safety controls consistent with industry standards.",
          action: "No action required — confirms current brand safety controls meet Ad Standards requirements.",
          sector_tags: ["general"],
          source: "Ad Standards",
        },
        {
          original_url: "https://www.accc.gov.au",
          section: "judgement",
          headline: "ACCC issues warning on subscription advertising disclosure",
          summary: "The ACCC has warned news publishers that subscription advertising must clearly disclose introductory pricing periods and automatic renewal terms, following complaints about misleading 'cancel anytime' claims.",
          action: "Review all subscription advertising to ensure introductory terms and renewal conditions are clearly disclosed.",
          sector_tags: ["general"],
          source: "ACCC",
        },
      ],
      under_review: [
        {
          original_url: "https://www.acma.gov.au",
          section: "under_review",
          headline: "ACMA reviewing digital news platform advertising classification",
          summary: "ACMA has opened a review into whether digital news platforms should be classified as broadcasting services for advertising regulatory purposes, which could significantly expand compliance obligations.",
          action: "Monitor this review — if digital platforms are reclassified, advertising compliance obligations will increase substantially.",
          sector_tags: ["general"],
          source: "ACMA",
        },
      ],
    },
    compliance_tip: "Ad Standards requires that sponsored content and native advertising be labelled in a manner immediately apparent to readers before they engage. 'Sponsored' or 'Advertisement' must appear prominently upfront — not at the end of the content.",
    sector_spotlight: "News and publications brands face increasing compliance pressure on advertorial and native content disclosure. APC and Ad Standards are actively reviewing cases where sponsored content is not immediately distinguishable from editorial. Key risk: subtle 'Sponsored' labels that appear only at the end of content. Practical tip: test your sponsored content labels with someone unfamiliar with your publication — if they can't identify it as advertising within 3 seconds, it needs clearer labelling.",
  },
};
